<a href="https://colab.research.google.com/github/Havokzbr/Trabalhos-Faculdade/blob/main/Aula_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Declarar as matrizes
A = np.array([[2,1],[1,2]])
B = np.array([[3.5],[2.5]])

# Encontrar a inversa de A
A_inversa = np.linalg.inv(A)

# Encontrar X
X = np.dot(A_inversa, B)

In [ ]:
print(X)

[[1.5]
 [0.5]]


In [ ]:
import numpy as np
print(np.random.randn(10))

[ 0.81089653  0.81219591  0.8499927  -0.63572634 -0.05868181  0.4467852
  0.32731551  0.655399    0.77083787  2.58470248]


NumPy

https://numpy.org/devdocs/user/quickstart.html

In [ ]:
import numpy as np
a = np.arange(15).reshape(3, 5)
print('matriz =',a)
print()
print('linhas x colunas = ',a.shape)
print()
print('dimensões = ',a.ndim)
print()
print('tipo dos elementos =',a.dtype.name)
print()
print('tamanho em bytes de cada elemento =',a.itemsize)
print()
print('quantidade de elementos na matriz =',a.size)
print()
print(type(a))
print()
b = np.array([6, 7, 8])
print(type(b))


matriz = [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

linhas x colunas =  (3, 5)

dimensões =  2

tipo dos elementos = int64

tamanho em bytes de cada elemento = 8

quantidade de elementos na matriz = 15

<class 'numpy.ndarray'>

<class 'numpy.ndarray'>
